### ISSUE TITLE
When adding new workouts the name wont change

### ISSUE THREAD

**Issue by rasky817** [Eclipsa2/gym_gram#2]
Basically the title. When adding new workouts the name generation does not work. It does not increase the number of workouts i have. It's only appearing as Workout #5. ![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYjZkYzE0M2I2Yjc5NTU2NGIyYzdjMDBhODMzZGFlYzI5YzE3NjA3YSZjdD1n/eM5TeMlCjyHcPfBPh6/giphy.gif)

**Comment by snichita817** [comment]
Fixed the error. It appears that the problem was with the get() method where it only took the number of workouts once, and then never updated it.
